[package]
name = "xattr-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
xattr = "1.5.0" # 确保版本兼容性，最新版可能不同
hex = "0.4"
image= "0.24.6" # 确保版本兼容性，最新版可能不同
byteorder = "1.3.4"
icns = { git = "https://github.com/samdenty/rust-icns", branch = "image-rs" }
